FROM docker-staging.imio.be/base:18.04

ARG repo=buildout.pm
RUN mkdir -p /home/imio/.buildout/downloads \
  && mkdir -p /home/imio/.buildout/eggs

ENV HOME=/home/imio
COPY default.cfg /home/imio/.buildout/default.cfg
RUN chown -R imio:imio /home/imio
RUN buildDeps="build-essential libpq-dev libreadline-dev wget git subversion libpcre3-dev libssl-dev libxml2-dev libxslt1-dev libbz2-dev libffi-dev libjpeg62-dev libopenjp2-7-dev zlib1g-dev python-dev python-pip virtualenv" \
  && cd /home/imio/ \
  && apt-get update \
  && apt-get full-upgrade -y \
  && apt-get install -y --no-install-recommends $buildDeps \
  && runDeps="graphicsmagick poppler-utils ruby libmagic-dev" \
  && apt-get install -y --no-install-recommends $runDeps \
  && gem install docsplit \
  && ln -sf /usr/bin/virtualenv /usr/local/bin/virtualenv-2.7

COPY --chown=imio eggs /home/imio/.buildout/eggs

USER imio
WORKDIR /home/imio/
RUN git clone https://github.com/IMIO/${repo}.git ${repo}

WORKDIR /home/imio/${repo}
RUN mkdir -p var/filestorage/ \
  && touch var/filestorage/Data.fs \
  && make buildout

WORKDIR /home/imio/
RUN rm -rf ${repo}

USER root
RUN apt-get purge -y $buildDeps \
  && apt-get autoremove -y \
  && apt-get clean autoclean \
  && rm -rf /home/imio/.buildout/downloads/ /var/lib/apt/lists/* /tmp/* /var/tmp/* /home/imio/.cache /home/imio/.local
