---
version: '3.4'
services:
  libreoffice:
    image: docker-staging.imio.be/libreoffice/server:latest
    read_only: false
    expose:
      - 8997/tcp
    tmpfs:
      - /var/tmp:rw
  zeo:
    image: docker-staging.imio.be/iadelib/mutual
    command: zeoserver start
    read_only: false
    volumes:
      - imio-pm:/home/imio/imio-pm/var
    ports:
      - 8100:8100
    tmpfs:
      - /var/tmp:rw,uid=913,gid=209
      - /home/imio/imio-pm/var/log:rw,uid=913,gid=209
    healthcheck:
      disable: true
  instance:
    image: docker-staging.imio.be/iadelib/mutual
    command: fg
    read_only: false
    environment:
      ZEO_ADDRESS: zeo:8100
    ports:
      - 8081:8081
    tmpfs:
      - /var/tmp:rw,uid=913,gid=209
      - /home/imio/imio-pm/var/instance:rw,uid=913,gid=209
volumes:
  imio-pm:
