name: 'Build and publish to dockerhub'
description: 'Build and publish to dockerhub'
inputs:
  DOCKERHUB_USERNAME:
    description: 'DOCKERHUB_USERNAME'
    required: true
  DOCKERHUB_PASSWORD:
    description: 'DOCKERHUB_PASSWORD'
    required: true
  profile:
    description: 'Buildout profile'
    required: true
    default: 'communes'
  tags:
    description: 'Tag name'
    required: false
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: ./docker/Dockerfile-latest
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_PASSWORD }}
    - name: Build image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.tags }}
        platforms: linux/amd64
        pull: true
        push: true
        build-args: PROFILE=${{ inputs.profile }}.cfg
