name: 'Build and publish to dockerhub'
description: 'Build and publish to dockerhub and IMIO container registry'
inputs:
  profile:
    description: 'Buildout profile'
    required: true
    default: 'communes'
  tags:
    description: 'Tag name'
    required: false
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: ./docker/Dockerfile-latest
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_URL }}
        username: ${{ secrets.DELIB_HARBOR_USERNAME }}
        password: ${{ secrets.DELIB_HARBOR_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.tags }}
        platforms: linux/amd64
        pull: true
        push: true
        build-args: PROFILE=${{ inputs.profile }}.cfg
