FROM imiobe/plone-base:4.3.20-debian as builder

ARG PROFILE="communes-dev.cfg"

USER root
RUN apt-get update \
  && apt-get full-upgrade -qqy \
  && devDeps="git subversion" \
  && mkdir -p /usr/share/man/man1 \
  && apt-get install -qqy --no-install-recommends \
     default-jre \
     libreoffice \
     libreoffice-script-provider-python \
     file \
     imagemagick \
     graphicsmagick \
     ghostscript \
     poppler-data \
     poppler-utils \
     ruby \
     libmagic1 \
     libjpeg62-turbo \
     libpng16-16 \
     libopenjp2-7 \
     libldap-2.4-2 \
     python-ldap \
     ldap-utils \
     libwebp6\
     libpq5 \
     lbzip2 \
     librsvg2-bin\
     libsigc++-2.0-0v5 \
  && apt-get purge libreoffice-gnome libreoffice-gtk* libreoffice-help* libreoffice-kde* \
  && buildDeps="build-essential \
                python-dev-is-python2 \
                cmake \
                make \
                wget \
                python-pip \
                python-wheel \
                libpq-dev \
                libreadline-dev \
                gcc \
                libc6-dev \
                libpcre3-dev \
                libssl-dev \
                libxml2-dev \
                libxslt1-dev \
                libbz2-dev \
                libffi-dev \
                libjpeg62-dev \
                libopenjp2-7-dev \
                zlib1g-dev \
                libldap2-dev \
                libwebp-dev \
                libsasl2-dev \
                libldap2-dev \
                python-ldap-dbg \
                libsigc++-2.0-dev" \
  && apt-get install -qqy --no-install-recommends $devDeps $buildDeps \
  && rm -rf /var/lib/apt/lists/* \
  && gem install docsplit \
  && wget -nv -O /home/imio/zint.tar.gz https://sourceforge.net/projects/zint/files/zint/2.9.1/zint-2.9.1-src.tar.gz/download \
  && tar -x -C /home/imio -f /home/imio/zint.tar.gz \
  && cd /home/imio/zint* \
  && cmake --log-level=ERROR . \
  && make --quiet \
  && make --quiet install

WORKDIR /plone

COPY --chown=imio *.cfg *.conf requirements.txt Makefile /plone/

RUN sed -i "s/\${buildout:directory}\/var/\/data/g" *.cfg \
  && echo "[buildout]" > buildout.cfg \
  && echo "extends =" >> buildout.cfg \
  && echo "    $PROFILE" >> buildout.cfg \
  && echo "    amqp.cfg" >> buildout.cfg \
  && echo "    ldap.cfg" >> buildout.cfg \
  && echo "    docker.cfg" >> buildout.cfg \
  && su -c "virtualenv -p python2 ." -s /bin/sh imio \
  && su -c "bin/pip install -r requirements.txt" -s /bin/sh imio \
  && su -c "bin/buildout -t 30 -N" -s /bin/sh imio \
  && rm -rf develop-eggs/ src/ var/blobstorage/ var/filestorage/

USER imio