version: '3.4'
services:
  libreoffice:
    image: imiobe/iadelib:test
    command: soffice --invisible --headless --nologo --nofirststartwizard --nodefault --accept="socket,host=libreoffice,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager"
    expose:
      - "2002"
    volumes:
      - tmp:/tmp
  instance:
    image: imiobe/iadelib:test
    links:
      - "libreoffice:oo"
    environment:
        - HTTP_PORT=8081
        - HOSTNAME_HOST=local
        - PROJECT_ID=plone
        - CUSTOM_TMP=/tmp
        - OO_SERVER=libreoffice
        - OO_PORT=2002
        - USE_STREAM=False
    volumes:
      - tmp:/tmp
    command: bin/testmc

volumes:
  tmp: