FROM imiobe/iadelib:base as builder

ARG PROFILE="communes.cfg"

WORKDIR /plone
USER root
COPY --chown=imio *.cfg *.conf requirements.txt Makefile /plone/
RUN apt-get update \
  && apt-get full-upgrade -qqy \
  && apt-get install -qqy --no-install-recommends \
     lynx \
     openjdk-18-jre-headless \
     libreoffice \
     libreoffice-script-provider-python \
     file \
     imagemagick \
     graphicsmagick \
     ghostscript \
     poppler-data \
     ruby \
     libmagic1 \
     libldap-2.5-0 \
     ldap-utils \
     libpq5 \
     lbzip2 \
     libsigc++-2.0-0v5 \
  && apt-get purge -qqy libreoffice-gnome libreoffice-gtk* libreoffice-help* libreoffice-kde* \
  && buildDeps="build-essential \
        python2-dev \
        cmake \
        make \
        python3-pip \
        wget \
        git \
        gcc \
        libpq-dev \
        libreadline-dev \
        libc6-dev \
        libpcre3-dev \
        libssl-dev \
        libssl-dev \
        libxml2-dev \
        libxslt1-dev \
        libbz2-dev \
        zlib1g-dev \
        libldap2-dev \
        libsasl2-dev \
        libldap2-dev \
        libsigc++-2.0-dev \
        libffi-dev \
        libjpeg62-dev \
        libopenjp2-7-dev \
        libwebp-dev \
        libgif-dev \
        zlib1g-dev \
        libwebp-dev" \
  && apt-get install -qqy --no-install-recommends $buildDeps \
  && rm -rf /var/lib/apt/lists/* \
  && pip install "virtualenv>=20.7.2" \
  && gem install docsplit \
  && sed -i "s/\${buildout:directory}\/var/\/data/g" *.cfg \
  && echo "[buildout]" > buildout.cfg \
  && echo "extends =" >> buildout.cfg \
  && echo "    $PROFILE" >> buildout.cfg \
  && echo "    amqp.cfg" >> buildout.cfg \
  && echo "    ldap.cfg" >> buildout.cfg \
  && echo "    docker.cfg" >> buildout.cfg \
  && sed -ie "s#Products.MeetingCommunes:zcity#Products.MeetingCommunes:demo#" *.cfg \
  && su -c "virtualenv -p python2 ." -s /bin/sh imio \
  && su -c "bin/pip install 'python-ldap==2.4.15' -r requirements.txt" -s /bin/sh imio \
  && su -c "bin/buildout -t 30 -N" -s /bin/sh imio \
  && rm -rf develop-eggs/ src/ var/blobstorage/ var/filestorage/ parts/instance? bin/instance?

FROM imiobe/iadelib:base
ENV DELIB_MAJOR=4.2

LABEL delib=$DELIB_VERSION \
      name="ia.Delib" \
      description="ia.Delib image, based on imiobe/plone-base:4.3.20-ubuntu-20.04" \
      maintainer="iMio"

COPY --from=builder /usr/local/lib/python2.7/dist-packages /usr/local/lib/python2.7/dist-packages

COPY --chown=imio --from=builder /plone /plone/
COPY --chown=imio docker/docker-initialize.py docker/*.sh /plone/
WORKDIR /plone
USER imio

ENV ZEO_ADDRESS=zeo:8100 \
 OO_SERVER=libreoffice \
 OO_PORT=2002 \
 PYTHON_UNO=/usr/bin/python3 \
 USE_STREAM=False \
 CUSTOM_TMP=/var/tmp \
 ACTIVE_BIGBANG=False

EXPOSE 8081
ENTRYPOINT ["/plone/docker-entrypoint.sh"]
CMD ["instance"]
