FROM imiobe/iadelib:buster-latest

ENV ZC_BUILDOUT=2.13.1 \
    SETUPTOOLS=40.8.0 \
    PIP=20.2.2

ARG PROFILE="communes-dev.cfg"

USER root
WORKDIR /plone

RUN apt-get update -qqy \
  && apt-get full-upgrade -qqy \
  && devDeps="git subversion" \
  && buildDeps="build-essential \
                cmake \
                make \
                wget \
                python-pip \
                libpq-dev \
                libreadline-dev \
                gcc \
                libc6-dev \
                libpcre3-dev \
                libssl-dev \
                libxml2-dev \
                libxslt1-dev \
                libbz2-dev \
                libffi-dev \
                libjpeg62-turbo-dev \
                libopenjp2-7-dev \
                zlib1g-dev \
                libldap2-dev \
                libwebp-dev \
                libsasl2-dev \
                libldap2-dev \
                python-ldap-dbg \
                librsvg2-dev \
                libsigc++-2.0-dev" \
  && apt-get install -qqy --no-install-recommends $devDeps $buildDeps \
  && rm -rf /var/lib/apt/lists/*

COPY --chown=imio *.cfg *.conf Makefile /plone/

USER imio

RUN echo "[buildout]" > buildout.cfg \
  && echo "extends =" >> buildout.cfg \
  && echo "    $PROFILE" >> buildout.cfg \
  && echo "    restapi.cfg" >> buildout.cfg \
  && echo "    amqp.cfg" >> buildout.cfg \
  && echo "    ldap.cfg" >> buildout.cfg \
  && echo "    docker.cfg" >> buildout.cfg \
  && touch /data/filestorage/Data.fs \
  && pip install pip==$PIP setuptools==$SETUPTOOLS zc.buildout==$ZC_BUILDOUT \
  && buildout -t 30
