FROM imiobe/plone-base:4.3.20-ubuntu as builder

ARG PROFILE="communes.cfg"

WORKDIR /
USER root
RUN add-apt-repository ppa:libreoffice/libreoffice-still \
  && apt-get update \
  && apt-get full-upgrade -qqy \
  # needed because of jre installation bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199#23
  && mkdir -p /usr/share/man/man1 \
  && apt-get install -qqy --no-install-recommends \
     default-jre \
     libreoffice \
     libreoffice-script-provider-python \
     file \
     imagemagick \
     graphicsmagick \
     ghostscript \
     poppler-data \
     poppler-utils \
     ruby \
     libmagic1 \
     libjpeg62 \
     libpng16-16 \
     libopenjp2-7 \
     libldap-2.4-2 \
     ldap-utils \
     libwebp6\
     libpq5 \
     lbzip2 \
     librsvg2-bin\
     libsigc++-2.0-0v5 \
  && apt-get purge libreoffice-gnome libreoffice-gtk* libreoffice-help* libreoffice-kde* \
  && buildDeps="build-essential \
                python-dev-is-python2 \
                cmake \
                make \
                wget \
                python3-pip \
                libpq-dev \
                libreadline-dev \
                gcc \
                libc6-dev \
                libpcre3-dev \
                libssl-dev \
                libxml2-dev \
                libxslt1-dev \
                libbz2-dev \
                libffi-dev \
                libjpeg62-dev \
                libopenjp2-7-dev \
                zlib1g-dev \
                libldap2-dev \
                libwebp-dev \
                libsasl2-dev \
                libldap2-dev \
                libsigc++-2.0-dev" \
  && apt-get install -qqy --no-install-recommends $buildDeps \
  && rm -rf /var/lib/apt/lists/* \
  && pip install "virtualenv>=20.7.2" \
  && gem install docsplit \
  && wget -nv -O /home/imio/zint.tar.gz https://sourceforge.net/projects/zint/files/zint/2.9.1/zint-2.9.1-src.tar.gz/download \
  && tar -x -C /home/imio -f /home/imio/zint.tar.gz \
  && cd /home/imio/zint-* \
  && cmake --log-level=ERROR . \
  && make --quiet \
  && make --quiet install

WORKDIR /plone

COPY --chown=imio *.cfg *.conf requirements.txt Makefile /plone/

RUN sed -i "s/\${buildout:directory}\/var/\/data/g" *.cfg \
  && echo "[buildout]" > buildout.cfg \
  && echo "extends =" >> buildout.cfg \
  && echo "    $PROFILE" >> buildout.cfg \
  && echo "    amqp.cfg" >> buildout.cfg \
  && echo "    ldap.cfg" >> buildout.cfg \
  && echo "    docker.cfg" >> buildout.cfg \
  && su -c "virtualenv -p python2 ." -s /bin/sh imio \
  && su -c "bin/pip install -r requirements.txt" -s /bin/sh imio \
  && su -c "bin/buildout -t 30 -N" -s /bin/sh imio \
  && rm -rf develop-eggs/ src/ var/blobstorage/ var/filestorage/

FROM imiobe/plone-base:4.3.20-ubuntu
ENV DELIB_MAJOR=4.2

LABEL delib=$DELIB_VERSION \
      name="ia.Delib" \
      description="ia.Delib image, based on imiobe/plone-base:4.3.20-debian" \
      maintainer="iMio"

COPY --from=builder /usr/local/lib/python2.7/dist-packages /usr/local/lib/python2.7/dist-packages
COPY --from=builder /usr/local/lib/libzint.so.2.9.0 /usr/local/lib/libzint.so.2.9 /usr/local/lib/libzint.so /usr/local/lib/
COPY --from=builder /usr/local/include/zint.h /usr/local/include/
COPY --from=builder /usr/local/bin/zint /usr/local/bin/

COPY --chown=imio --from=builder /plone /plone/
COPY --chown=imio docker/docker-initialize.py docker/docker-entrypoint.sh docker/update-admin-password.py /plone/

RUN add-apt-repository ppa:libreoffice/libreoffice-still \
  && apt-get update \
  && apt-get full-upgrade -qqy -q \
  # needed because of jre installation bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199#23
  && mkdir -p /usr/share/man/man1 \
  && apt-get install -qqy --no-install-recommends \
     python-is-python2 \
     default-jre \
     libreoffice \
     libreoffice-script-provider-python \
     file \
     imagemagick \
     graphicsmagick \
     ghostscript \
     poppler-data \
     poppler-utils \
     ruby \
     libmagic1 \
     libjpeg62 \
     libpng16-16 \
     libopenjp2-7 \
     libldap-2.4-2 \
     ldap-utils \
     libwebp6\
     libpq5 \
     lbzip2 \
     libsigc++-2.0-0v5 \
  && apt-get purge libreoffice-gnome libreoffice-gtk* libreoffice-help* libreoffice-kde* \
  && rm -rf /var/lib/apt/lists/* \
  && gem install docsplit \
  && bin/pip install -r requirements.txt \
  && chmod +x /plone/docker-entrypoint.sh

WORKDIR /plone

USER imio

ENV ZEO_ADDRESS=zeo:8100 \
 OO_SERVER=libreoffice \
 OO_PORT=2002 \
 USE_STREAM=False \
 CUSTOM_TMP=/var/tmp

EXPOSE 8081
ENTRYPOINT ["/plone/docker-entrypoint.sh"]
CMD ["start"]
