version: "2.4"
services:
  loffice:
    image: imiobe/libreoffice:7.3
    command: soffice --headless --nodefault --accept="socket,host=loffice,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager"
    expose:
      - "2002"
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    networks:
      - loffice
    environment:
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
    mem_limit: 200M
    mem_reservation: 200M
    mem_swappiness: 0

  instance:
    image: imiobe/iadelib:dev
    command: bin/testmc -t testAdvice
    depends_on:
      - loffice
    networks:
      - default
      - loffice
    environment:
      - HTTP_PORT=8081
      - ZEO_ADDRESS=db:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - CUSTOM_TMP=/var/tmp
      - OO_SERVER=loffice
      - OO_PORT=2002
      - USE_STREAM=False
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    mem_limit: 1224M
    mem_reservation: 1124M

volumes:
  tmp:
  vartmp:

networks:
  loffice:
    internal: true