version: '2'
services:
  my_lo:
    image: imiobe/libreoffice:6.1
    command: soffice --headless --nodefault --accept="socket,host=libreoffice,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager"
    expose:
      - "2002"
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    networks:
      - my_lo
    mem_limit: 200M
    mem_reservation: 200M

  instance:
    image: imiobe/iadelib:dev
    command: bin/testmc
    depends_on:
      - my_lo
    networks:
      - my_lo
    environment:
      - HTTP_PORT=8081
      - ZEO_ADDRESS=db:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - CUSTOM_TMP=/var/tmp
      - OO_SERVER=my_lo
      - OO_PORT=2002
      - USE_STREAM=False
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    mem_limit: 1224M
    mem_reservation: 1124M

volumes:
  tmp:
  vartmp:

networks:
  my_lo: