FROM imiobe/iadelib:4.1-dev

ENV ZC_BUILDOUT=2.13.1 \
    SETUPTOOLS=40.8.0 \
    PIP=20.2.2

ARG PROFILE="communes-dev.cfg"
ARG PR_NUM=''
ARG PR_REPO=''

USER root
WORKDIR /plone

COPY --chown=imio *.cfg *.conf Makefile .coveragerc /plone/

USER imio
ENV PATH="/home/imio/.local/bin:${PATH}"

RUN rm -fr bin include lib local share downloads .installed.cfg \
  && echo "[buildout]" > buildout.cfg \
  && echo "extends =" >> buildout.cfg \
  && echo "    $PROFILE" >> buildout.cfg \
  && echo "    restapi.cfg" >> buildout.cfg \
  && echo "    amqp.cfg" >> buildout.cfg \
  && echo "    ldap.cfg" >> buildout.cfg \
  && echo "    docker.cfg" >> buildout.cfg \
  && echo "Bouildout config :" \
  && cat buildout.cfg \
  && pip install -U pip==$PIP setuptools==$SETUPTOOLS zc.buildout==$ZC_BUILDOUT coverage coveralls \
  && buildout -t 60 \
  && if [ -z $PR_NUM ] || [ -z $PR_REPO ] ; \
     then echo "Argument PR_NUM or PR_REPO not provided" ; \
     else cd src/$PR_REPO \
          && git fetch origin pull/$PR_NUM/head:PR-$PR_NUM \
          && git checkout PR-$PR_NUM \
          && cd /plone \
          && buildout -t 60; \
     fi

WORKDIR /plone