version: '3.4'
services:
  libreoffice:
    image: imiobe/libreoffice:6.1
    command: soffice --headless --nodefault --accept="socket,host=libreoffice,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager"
    expose:
      - "2002"
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    networks:
      - libreoffice

  instance:
    image: imiobe/iadelib:dev
    depends_on:
      - libreoffice
    networks:
      - libreoffice
    environment:
      - HTTP_PORT=8081
      - ZEO_ADDRESS=db:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - CUSTOM_TMP=/var/tmp
      - OO_SERVER=libreoffice
      - OO_PORT=2002
      - USE_STREAM=False
    volumes:
      - tmp:/tmp
      - vartmp:/var/tmp
    command: bin/testmc

volumes:
  tmp:
  vartmp:

networks:
  libreoffice: