name: Update base image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish to dockerhub
        uses: IMIO/buildout.pm/actions/dockerhub@master
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: imiobe/iadelib:base
          dockerfile: ./docker/Dockerfile-base