name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build latest
        uses: IMIO/buildout.pm/actions/harbor@master
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          HARBOR_URL: ${{ secrets.HARBOR_URL }}
          DELIB_HARBOR_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          DELIB_HARBOR_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          tags: |
            imiobe/iadelib:latest
            "${{ secrets.HARBOR_URL }}/delib/iadelib:latest"
          dockerfile: ./docker/Dockerfile-latest
      - name: Build and publish dev image
        uses: IMIO/buildout.pm/actions/harbor@master
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          HARBOR_URL: ${{ secrets.HARBOR_URL }}
          DELIB_HARBOR_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          DELIB_HARBOR_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          tags: imiobe/iadelib:dev
          dockerfile: ./docker/Dockerfile-dev
          profile: communes-dev
