name: Update images

on:
  workflow_dispatch:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}

env:
  IMAGE_NAME: delib/iadelib

jobs:
  docker-latest:
    runs-on: gha-runners-delib-py3
    steps:
      - name: Build and publish communes image to harbor
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: '.'
          DOCKERFILE: './docker/Dockerfile-latest'
          BUILD_ARGS: 'PROFILE=communes.cfg'

  docker-dev:
    runs-on: gha-runners-delib-py3
    steps:  
      - name: Build and publish dev image
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:dev
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: '.'
          DOCKERFILE: './docker/Dockerfile-dev'
          BUILD_ARGS: 'PROFILE=communes-dev.cfg'
