name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build latest
        uses: IMIO/buildout.pm/actions/harbor@master
        with:
          tags: |
            imiobe/iadelib:latest
            "${{ secrets.HARBOR_URL }}/delib/iadelib:latest"
          dockerfile: ./docker/Dockerfile-latest
      - name: Build and publish dev image
        uses: IMIO/buildout.pm/actions/harbor@master
        with:
          tags: imiobe/iadelib:dev
          dockerfile: ./docker/Dockerfile-dev
          profile: communes-dev
