name: Update base image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00

env:
  IMAGE_NAME: delib/iadelib

jobs:
  base:
    runs-on: gha-runners-delib-py3
    steps:
      - name: Build and publish base image to harbor
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:base
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: '.'
          DOCKERFILE: './docker/Dockerfile-base'
