name: Update images
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *' # Weekly on Sundays at 02:00
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build base image
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./docker/Dockerfile-debian
          tags: imiobe/iadelib:buster-latest
          pull: true
          push: true
      - name: Build dev image
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./docker/Dockerfile-dev
          tags: imiobe/iadelib:dev
          pull: true
          push: true
