name: Test package

on:
  workflow_dispatch:
  push:
   branches:
     - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: IMIO/gha-workflows/.github/workflows/package-test-legacy.yml@v1
    secrets:
      gh_token: ${{ secrets.TOKEN_GITHUB_RO }}
      mattermost_webhook_url: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
    with:
      buildout_config_file: prod-test.cfg
      requirements_file: requirements.txt
      runner_label: gha-runners-delib-py2
      soffice: true
      test_command: OO_SERVER=localhost OO_PORT=2002 bin/testprod --layer=\!ROBOT --test=\!testSetup
